/**
 * HTML / React / Vue 三种产物共用的数据模型与文案字典。
 * ---------------------------------------------------------------------------
 * 之所以抽出来：三种产物必须「同一份数据、同一套文案、同一套配色」，
 * 否则改了 HTML 忘了改组件，文档里的样本就会撒谎。
 */
export const GEN_URL = 'https://github.com/aispin/iskill-generate-sponsors';

/** Markdown 产物（README 区块 / SPONSORS.md）里的固定文案 */
export const MD = {
  zh: { thanks: '感谢每一份支持' },
  en: { thanks: 'Thanks for every bit of support' },
};

/** 界面文案。用户自定义文案（标题/标语/备注）另有 en 版本，见 buildModel。 */
export const UI = {
  zh: {
    badge: '赞助支持',
    hint: '点击放大',
    linksTitle: '其他支持方式',
    altOf: '{x}收款码',
    zoomOf: '放大{x}收款码',
    themeAria: '切换深色 / 浅色',
    langAria: '切换中文 / English',
    closeAria: '关闭放大图',
    popAria: '打开赞助弹窗',
    popCloseAria: '关闭赞助弹窗',
    // 第二段（弹层入口）的文案 —— 页面固定两段式，这段是**访客口吻**，
    // 不出现命令行 / 形态名：这页同时是用户直接部署的赞助页，不是说明书。
    popSecTitle: '也可以点开看',
    popSecHint: '点下面的按钮，全部赞助方式会在弹层里重新排一遍。',
    langShort: 'EN',   // 当前为中文时，按钮上显示的「切到另一种语言」短标
    empty: '还没有配置外部赞助链接。加一个 <code>--paypal https://paypal.me/你的名字</code> 再来一次。',
  },
  en: {
    badge: 'SPONSOR',
    hint: 'Tap to enlarge',
    linksTitle: 'Other ways to support',
    altOf: '{x} QR code',
    zoomOf: 'Enlarge the {x} QR code',
    themeAria: 'Toggle dark / light mode',
    langAria: 'Switch between 中文 / English',
    closeAria: 'Close',
    popAria: 'Open sponsor popup',
    popCloseAria: 'Close sponsor popup',
    popSecTitle: 'Prefer a popup?',
    popSecHint: 'Tap the button below to see every option in a focused overlay.',
    langShort: '中',
    empty: 'No external sponsor links yet. Add one with <code>--paypal https://paypal.me/yourname</code>, then re-run.',
  },
};

/** 取 {zh,en} 双语文案；传进来的不是对象时原样返回（兼容纯字符串配置） */
export function pick(v, lang) {
  if (v === null || v === undefined) return '';
  if (typeof v !== 'object' || Array.isArray(v)) return String(v);
  if (v[lang] != null) return v[lang];
  return v.zh != null ? v.zh : (v.en != null ? v.en : '');
}

/** 某张收款码在指定语言下的 label / tip */
export function qrText(q, lang) {
  return {
    label: pick({ zh: q.label, en: q.labelEn || q.label }, lang),
    tip: pick({ zh: q.tip, en: q.tipEn || q.tip }, lang),
  };
}

/** {x} 占位符填充 —— 中英文语序不同，所以文案里用占位符而不是拼接 */
export const fill = (tpl, x) => String(tpl == null ? '{x}' : tpl).replace('{x}', x);

export function buildModel(opt, qrList, links) {
  const langs = Array.isArray(opt.langs) && opt.langs.length
    ? opt.langs.filter(l => l === 'zh' || l === 'en')
    : ['zh', 'en'];
  if (!langs.length) langs.push('zh');

  // 本地日期。⚠️ 别用 toISOString() —— 那是 UTC，东八区 0–8 点会退回前一天，
  // 页脚日期会「少一天」（2026-10-02 实锤：凌晨生成显示 10-01）。
  const now = new Date();
  const p2 = n => String(n).padStart(2, '0');
  const date = `${now.getFullYear()}-${p2(now.getMonth() + 1)}-${p2(now.getDate())}`;
  const a = `<a href="${GEN_URL}" target="_blank" rel="noopener noreferrer">iskill-generate-sponsors</a>`;

  return {
    defaultLang: opt.lang || 'zh',
    langs,
    title:    { zh: opt.title,             en: opt.titleEn   || opt.title },
    tagline:  { zh: opt.tagline,           en: opt.taglineEn || opt.tagline },
    note:     { zh: opt.footerNote,        en: opt.noteEn    || opt.footerNote },
    foot:     { zh: `由 ${a} 生成 · ${date}`, en: `Generated by ${a} · ${date}` },
    generatedAt: date,
    generator: { name: 'iskill-generate-sponsors', url: GEN_URL },
    ui: UI,
    qr: qrList.map(q => ({
      key: q.key,
      src: q.cSrc,
      accent: q.accent,
      label: { zh: q.label, en: q.labelEn || q.label },
      tip:   { zh: q.tip,   en: q.tipEn   || q.tip },
    })),
    links: links.map(l => ({
      label: l.label, sub: l.sub, url: l.url, accent: l.accent,
      // 二维码：默认引用落盘的 SVG 文件（Pages 镜像口径，与 qr.src 同基准）；
      // --standalone 仍内嵌 data URI，保「发给人就能看」的单文件形态
      qr: l.qr ? (opt.standalone ? l.qr : `${opt.pagesImgBase}/${l.svgFile}`) : null,
    })),
  };
}
